/**
 * `paths` must be reachable from every surface that lists commands, not just
 * from commander's generated `--help`.
 *
 * A command that exists but appears in no table is a command nobody runs. The
 * generated CLAUDE.md matters most of the three: it is the file coding agents
 * read to learn what this repo can answer, so an omission there means agents
 * keep inferring reachability from source instead of asking.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cmdPaths } from '../src/tui/commands.js';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p: string) => readFileSync(join(repoRoot, p), 'utf-8');

describe('paths is documented on every surface', () => {
  it('appears in the CLI command list in the reference doc', () => {
    expect(read('docs/GUARDLINK_REFERENCE.md')).toMatch(/guardlink paths \[dir\]/);
  });

  it('appears in the TUI command list in the reference doc', () => {
    expect(read('docs/GUARDLINK_REFERENCE.md')).toMatch(/^\/paths /m);
  });

  it('appears in the README', () => {
    expect(read('README.md')).toMatch(/guardlink paths/);
  });

  it('appears in the CLAUDE.md that init generates for every project', () => {
    // The template, not a generated artifact — the artifact is regenerated by
    // `guardlink sync` and would drift silently if only it were asserted on.
    expect(read('src/init/templates.ts')).toMatch(/guardlink paths \./);
  });

  it('is routed in the TUI dispatch table', () => {
    expect(read('src/tui/index.ts')).toMatch(/case '\/paths':/);
  });

  it('is listed in the TUI in-app help', () => {
    expect(read('src/tui/commands.ts')).toMatch(/'\/paths/);
  });

  it('is registered as an MCP tool, the surface agents actually call', () => {
    expect(read('src/mcp/server.ts')).toMatch(/'guardlink_paths'/);
  });

  it('is listed in the MCP tool roster the generated CLAUDE.md advertises', () => {
    expect(read('src/init/templates.ts')).toMatch(/guardlink_paths/);
  });
});

describe('cmdPaths', () => {
  it('is exported so the dispatch table has something to call', () => {
    expect(typeof cmdPaths).toBe('function');
  });
});
