---
name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      value: |
        1. Run `guardlink ...`
        2. ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: GuardLink version
      description: Output of `guardlink --version`
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      description: Output of `node --version`
      placeholder: "v22.0.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true
